# Generated by Django 2.1.2 on 2018-10-13 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181012_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='RFID',
        ),
        migrations.AddField(
            model_name='cab_history',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment_History',
        ),
    ]
